child_process(85692)::clone(https://github.com/GoogleCloudPlatform/cloud-debug-python):stderr:data: Cloning into 'C:\GRD\GCP--12-01-2018--hxtfbAqYXq9fmfHKYnFAtq\cloud-debug-python'...
fatal: unable to access 'https://github.com/GoogleCloudPlatform/cloud-debug-python/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
child_process(85692)::clone(https://github.com/GoogleCloudPlatform/cloud-debug-python):close():error: with status: 128